VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "vertx" do |vertx|
      	vertx.vm.provider "docker" do |d|
      		  ##Docker container configuration and launch configuration
     	  		d.build_dir = "."
     	  		##check out ssh in container, not working
        		#d.has_ssh = true
        		d.build_args = ["-t=vertxdev"]
        		##IE : 8181 from boot2docker is mapped to 8080 inside the container
        		d.ports = ["8181:8080"]
            ##name for the container
        		d.name = "vertxdev"
        		d.remains_running = true
            ##DEFINE ENVIRONMENT VARIABLE
        		##startup command
        		d.cmd = ["vertx", "run", "vertx-examples/src/raw/java/httphelloworld/HelloWorldServer.java"]
        		##mounting boot2docker VM volume to the container, ONE WAY rsync ! 
        		d.volumes = ["/docker-host:/docker-host"]
            ##Comment the line below if you are running on a linux host
        		d.vagrant_vagrantfile = "../docker-host/Vagrantfile"
      	end
    		##ssh configuration for vertx VM but not the docker container
    		vertx.ssh.username = "docker"
    		#vertx.ssh.password = "tcuser"
    		##mdp : tcuser
     		vertx.ssh.host = "127.0.0.1"
     		vertx.ssh.port = 22
     		vertx.vm.boot_timeout = 30
    end  
end