VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.define "nodejs" do |nodejs|
		nodejs.vm.provider "docker" do |d|
			d.image = "node:latest"
			d.name = "nodedev"
			d.cmd = ["node", "/vagrant/app.js"]
			d.ports = ["8282:80"]
			d.remains_running = true
			##Comment the line below if you are running on a linux host
			d.vagrant_vagrantfile = "../docker-host/Vagrantfile"
		end
  		##ssh configuration for nodejs VM but not the docker container
  		nodejs.ssh.username = "docker"
  		#nodejs.ssh.password = "tcuser"
  		##mdp : tcuser
   		nodejs.ssh.host = "127.0.0.1"
   		nodejs.ssh.port = 22
   		nodejs.vm.boot_timeout = 30
	end	
end