# Copied from https://github.com/mitchellh/vagrant/blob/master/plugins/providers/docker/hostmachine/Vagrantfile

Vagrant.configure("2") do |config|

  config.vm.box = "mitchellh/boot2docker"

  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end

  # b2d doesn't support NFS
  config.nfs.functional = false

  config.vm.network "forwarded_port",
    guest: 8181, host: 8181

  config.vm.synced_folder ".", "/app"

  ##Already done by vagrant ??
  #config.vm.network "forwarded_port",
  #  guest: 2222, host: 22

  # not available in tinycore linux (boot2docker)
  #config.vm.hostname = "Docker-host-VM"

end